export const videoData = [
  {
    id: 7,
    imageUrl: '/bitcoin.jpg',
    logo: '/start1.svg', 
    title: 'Donate TEA to OSS projects', 
    description: 'How to donate TEA to OSS projects.',
    name: 'Tea Protocol',
    videoUrl: 'https://m.youtube.com/watch?v=Gn9whvjwmYo&t=20s',
    certificatePrice:  '0.01',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
 },
 {
   id: 8,
   imageUrl: '/feature1.svg' ,
   logo: '/start1.svg', 
   title: 'Jason Coombs & Max Howel', 
   description: 'Jason Coombs & Max Howel - AMA',
   name: 'Tea Protocol',
   videoUrl: 'https://m.youtube.com/watch?v=VYx6KZJLh94',
   certificatePrice:  '0.01',
   tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
},
{
 id: 9,
 imageUrl: '/Wallets.jpg' ,
 logo: '/start1.svg', 
 title: 'Stake and unstake tea', 
 description: 'How to stake and unstake tea',
 name: 'Tea Protocol',
 videoUrl: 'https://m.youtube.com/watch?v=BZvuRtQDniE',
 certificatePrice:  '0.000000001',
 tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
},
  ];

  export const PopularCertificateCourse = [
    {
      id: 1,
      imageUrl: '/bitcoin.jpg',
      logo: '/start1.svg', 
      title: 'Donate TEA to OSS projects', 
      description: 'How to donate TEA to OSS projects.',
      name: 'Tea Protocol',
      videoUrl: 'https://m.youtube.com/watch?v=Gn9whvjwmYo&t=20s',
      certificatePrice:  '0.01',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
   {
    id: 2,
    imageUrl: '/feature1.svg' ,
    logo: '/start1.svg', 
    title: 'Jason Coombs & Max Howel', 
    description: 'Jason Coombs & Max Howel - AMA',
    name: 'Tea Protocol',
    videoUrl: 'https://m.youtube.com/watch?v=VYx6KZJLh94',
    certificatePrice:  '0.01',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
 },
 {
  id: 3,
  imageUrl: '/Wallets.jpg' ,
  logo: '/start1.svg', 
  title: 'Stake and unstake tea', 
  description: 'How to stake and unstake tea',
  name: 'Tea Protocol',
  videoUrl: 'https://m.youtube.com/watch?v=BZvuRtQDniE',
  certificatePrice:  '0.000000001',
  tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
 },
  ];

  export const NewCertificateCourse = [
    {
      id: 4,
      imageUrl: '/feature1.svg' ,
      logo: '/start1.svg', 
      title: 'Jason Coombs & Max Howel', 
      description: 'Jason Coombs & Max Howel - AMA',
      name: 'Tea Protocol',
      videoUrl: 'https://m.youtube.com/watch?v=VYx6KZJLh94',
      certificatePrice:  '0.01',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
   {
    id: 5,
    imageUrl: '/feature1.svg' ,
    logo: '/start1.svg', 
    title: 'Jason Coombs & Max Howel', 
    description: 'Jason Coombs & Max Howel - AMA',
    name: 'Tea Protocol',
    videoUrl: 'https://m.youtube.com/watch?v=VYx6KZJLh94',
    certificatePrice:  '0.01',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
 },
 {
  id: 6,
  imageUrl: '/Wallets.jpg' ,
  logo: '/start1.svg', 
  title: 'Stake and unstake tea', 
  description: 'How to stake and unstake tea',
  name: 'Tea Protocol',
  videoUrl: 'https://m.youtube.com/watch?v=BZvuRtQDniE',
  certificatePrice:  '0.000000001',
  tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
 },
  ];
  

  