export const videoData = [
    {
      id: 8,
      title: "Introduction to Web3",
      url: "https://www.youtube.com/watch?v=LXb3EKWsInQ",
      platform: "YouTube",
      description: "A beginner's guide to understanding Web3 technology.",
      imageUrl: "/feature1.svg",
      name: "Educhain",
      videoUrl: 'https://youtu.be/6R_er-V81nI?si=NJ_N9Q6WD-2NBxXa',
      certificatePrice:  '0.000000001',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",

    },
    {
      id: 9,
      title: "How Web3 is Changing the Internet",
      url: "https://www.facebook.com/share/r/Aqu2XXMGV3BgHWMm/?mibextid=oFDknk",
      platform: "Facebook",
      description: "An overview of how Web3 is disrupting traditional internet structures.",
      imageUrl: "/feature1.svg",
      name: "Educhain",
      videoUrl: 'https://youtu.be/6R_er-V81nI?si=NJ_N9Q6WD-2NBxXa',
      certificatePrice:  '0.000000001',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",

    },
    {
      id: 10,
      title: "Building DApps on Ethereum",
      url: "https://www.linkedin.com/video/987654321",
      platform: "LinkedIn",
      description: "Learn how to build decentralized applications (DApps) on Ethereum.",
      imageUrl: "/feature1.svg",
      name: "Educhain",
      videoUrl: 'https://youtu.be/6R_er-V81nI?si=NJ_N9Q6WD-2NBxXa',
      certificatePrice:  '0.000000001',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
    }
  ];

  export const PopularCertificateCourse = [
    {
       id: 1,
       imageUrl: '/feature1.svg' ,
       logo: '/start1.svg', 
       title: 'Ethereum Basics', 
       description: 'What is Ethereum? Discover the “new internet” and unlock your digital freedom through the power of decentralized technology.',
       name: 'Educhain',
       videoUrl: 'https://youtu.be/6R_er-V81nI?si=NJ_N9Q6WD-2NBxXa',
       certificatePrice:  '0.000000001',
       tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
    },
    {
      id: 2,
      imageUrl: '/feature1.svg' ,
      logo: '/start1.svg', 
      title: 'Ethereum Basics 2', 
      description: 'What is Ethereum? Discover the “new internet” and unlock your digital freedom through the power of decentralized technology.',
      name: 'Educhain',
      videoUrl: 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
      certificatePrice:  '0.000000001',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
   {
    id: 3,
    imageUrl: '/feature1.svg' ,
    logo: '/start1.svg', 
    title: 'Ethereum Basics 3', 
    description: 'What is Ethereum? Discover the “new internet” and unlock your digital freedom through the power of decentralized technology.',
    name: 'Educhain',
    videoUrl: 'https://youtu.be/6R_er-V81nI?si=rqFVDeiq00Toedsf',
    certificatePrice:  '0.000000001',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
   {
    id: 4,
    imageUrl: '/feature1.svg' ,
    logo: './start1.svg', 
    title: 'Ethereum Basics 4', 
    description: 'What is Ethereum? Discover the “new internet” and unlock your digital freedom through the power of decentralized technology.',
    name: 'Educhain',
    videoUrl: 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
    certificatePrice:  '0.000000001',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
 },
  ];

  export const NewCertificateCourse = [
    {
       id: 5,
       imageUrl: '/feature1.svg' ,
       logo: './start1.svg', 
       title: 'New Ethereum Basics', 
       description: 'New What is Ethereum? Discover the “new internet” and unlock your digital freedom through the power of decentralized technology.',
       name: 'Educhain',
       videoUrl: 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
       certificatePrice:  '0.000000001',
       tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
    },
    {
      id: 6,
      imageUrl: '/feature1.svg' ,
      logo: './start1.svg', 
      title: 'Ethereum Basics', 
      description: 'What is Ethereum? Discover the “new internet” and unlock your digital freedom through the power of decentralized technology.',
      name: 'Educhain',
      videoUrl: 'https://youtu.be/6R_er-V81nI?si=NJ_N9Q6WD-2NBxXa',
      certificatePrice:  '0.000000001',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
   {
    id: 7,
    imageUrl: '/feature1.svg' ,
    logo: './start1.svg', 
    title: 'Ethereum Basics', 
    description: 'What is Ethereum? Discover the “new internet” and unlock your digital freedom through the power of decentralized technology.',
    name: 'Educhain',
    videoUrl: 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
    certificatePrice:  '0.000000001',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
  ];
  

  