export const videoData = [
  {
    id: 7,
    imageUrl: '/bitcoin.jpg' ,
    logo: '/start1.svg', 
    title: 'Bitcoin Basics', 
    description: 'Understanding Bitcoin: Revolutionizing Money and Financial Freedom In 2009, an anonymous figure known as Satoshi Nakamoto launched Bitcoin, sparking a global conversation about the future of money. For centuries, the control of money has rested in the hands of governments and banks, but Bitcoin introduces the idea that it should be in the hands of everyday citizens. This shift in control is crucial, as most of us don’t fully understand how little control we have over our money today.',
    name: 'Educhain',
    videoUrl: 'https://www.youtube.com/watch?v=bBC-nXj3Ng4',
    certificatePrice:  '0.01',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
 },
 {
   id: 8,
   imageUrl: '/feature1.svg' ,
   logo: '/start1.svg', 
   title: 'Ethereum Basics', 
   description: 'Over the last 40 years, the internet has become the global hub where people connect, trade ideas, goods, and services, and even fuel global movements. However, this powerful tool has a major flaw: it’s controlled by a small group of centralized services. Companies like Google, Apple, and Facebook have immense power over the online experiences of billions of people. These “walled gardens” limit our freedom with their rules, fees, and control, acting as intermediaries between users and their interactions.',
   name: 'Educhain',
   videoUrl: 'https://www.youtube.com/watch?v=jxLkbJozKbY',
   certificatePrice:  '0.01',
   tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
},
{
 id: 9,
 imageUrl: '/Wallets.jpg' ,
 logo: '/start1.svg', 
 title: 'Wallets basics', 
 description: 'Reclaiming Control: The Power of Crypto Wallets in a Decentralized Internet. The internet has evolved into humanity’s most powerful tool for connection, creativity, and innovation. Yet, despite its global reach, it’s dominated by centralized corporations that control much of what we do online. From banks managing your financial transactions to social platforms monitoring your interactions, intermediaries hold immense power over your digital exchanges. But what if you could take back control? This is where crypto wallets and decentralized applications (dApps) come in, enabling you to own your digital identity and assets.',
 name: 'Educhain',
 videoUrl: 'https://www.youtube.com/watch?v=MxmdGUyF7Zw',
 certificatePrice:  '0.000000001',
 tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
},
  ];

  export const PopularCertificateCourse = [
    {
       id: 1,
       imageUrl: '/bitcoin.jpg' ,
       logo: '/start1.svg', 
       title: 'Bitcoin Basics', 
       description: 'Understanding Bitcoin: Revolutionizing Money and Financial Freedom In 2009, an anonymous figure known as Satoshi Nakamoto launched Bitcoin, sparking a global conversation about the future of money. For centuries, the control of money has rested in the hands of governments and banks, but Bitcoin introduces the idea that it should be in the hands of everyday citizens. This shift in control is crucial, as most of us don’t fully understand how little control we have over our money today.',
       name: 'Educhain',
       videoUrl: 'https://www.youtube.com/watch?v=bBC-nXj3Ng4',
       certificatePrice:  '0.01',
       tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
    },
    {
      id: 2,
      imageUrl: '/feature1.svg' ,
      logo: '/start1.svg', 
      title: 'Ethereum Basics', 
      description: 'Over the last 40 years, the internet has become the global hub where people connect, trade ideas, goods, and services, and even fuel global movements. However, this powerful tool has a major flaw: it’s controlled by a small group of centralized services. Companies like Google, Apple, and Facebook have immense power over the online experiences of billions of people. These “walled gardens” limit our freedom with their rules, fees, and control, acting as intermediaries between users and their interactions.',
      name: 'Educhain',
      videoUrl: 'https://www.youtube.com/watch?v=jxLkbJozKbY',
      certificatePrice:  '0.01',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
   {
    id: 3,
    imageUrl: '/Wallets.jpg' ,
    logo: '/start1.svg', 
    title: 'Wallets basics', 
    description: 'Reclaiming Control: The Power of Crypto Wallets in a Decentralized Internet. The internet has evolved into humanity’s most powerful tool for connection, creativity, and innovation. Yet, despite its global reach, it’s dominated by centralized corporations that control much of what we do online. From banks managing your financial transactions to social platforms monitoring your interactions, intermediaries hold immense power over your digital exchanges. But what if you could take back control? This is where crypto wallets and decentralized applications (dApps) come in, enabling you to own your digital identity and assets.',
    name: 'Educhain',
    videoUrl: 'https://www.youtube.com/watch?v=MxmdGUyF7Zw',
    certificatePrice:  '0.000000001',
    tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
  ];

  export const NewCertificateCourse = [
    {
      id: 4,
      imageUrl: '/feature1.svg' ,
      logo: '/start1.svg', 
      title: 'Bitcoin Basics', 
      description: 'Understanding Bitcoin: Revolutionizing Money and Financial Freedom In 2009, an anonymous figure known as Satoshi Nakamoto launched Bitcoin, sparking a global conversation about the future of money. For centuries, the control of money has rested in the hands of governments and banks, but Bitcoin introduces the idea that it should be in the hands of everyday citizens. This shift in control is crucial, as most of us don’t fully understand how little control we have over our money today.',
      name: 'Educhain',
      videoUrl: 'https://www.youtube.com/watch?v=bBC-nXj3Ng4',
      certificatePrice:  '0.01',
      tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
   },
   {
     id: 5,
     imageUrl: '/feature1.svg' ,
     logo: '/start1.svg', 
     title: 'Ethereum Basics', 
     description: 'Over the last 40 years, the internet has become the global hub where people connect, trade ideas, goods, and services, and even fuel global movements. However, this powerful tool has a major flaw: it’s controlled by a small group of centralized services. Companies like Google, Apple, and Facebook have immense power over the online experiences of billions of people. These “walled gardens” limit our freedom with their rules, fees, and control, acting as intermediaries between users and their interactions.',
     name: 'Educhain',
     videoUrl: 'https://www.youtube.com/watch?v=jxLkbJozKbY',
     certificatePrice:  '0.01',
     tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
  },
  {
   id: 6,
   imageUrl: '/Wallets.jpg' ,
   logo: '/start1.svg', 
   title: 'Wallets basics', 
   description: 'Reclaiming Control: The Power of Crypto Wallets in a Decentralized Internet. The internet has evolved into humanity’s most powerful tool for connection, creativity, and innovation. Yet, despite its global reach, it’s dominated by centralized corporations that control much of what we do online. From banks managing your financial transactions to social platforms monitoring your interactions, intermediaries hold immense power over your digital exchanges. But what if you could take back control? This is where crypto wallets and decentralized applications (dApps) come in, enabling you to own your digital identity and assets.',
   name: 'Educhain',
   videoUrl: 'https://www.youtube.com/watch?v=MxmdGUyF7Zw',
   certificatePrice:  '0.000000001',
   tokenURI: "https://ipfs.filebase.io/ipfs/QmQ5rSc4LrRTUSMawpYwLK35rVW4nPgaj3TUBCcpvGVXFh",
  },
  ];
  

  